/*
 * Gearsystem - Sega Master System / Game Gear Emulator
 * Copyright (C) 2013  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/ 
 * 
 */

#ifndef OPCODEFDCB_NAMES_H
#define	OPCODEFDCB_NAMES_H

static stOPCodeInfo kOPCodeFDCBNames[256] = {
    { "RLC (IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "RLC (IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "RLC (IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "RLC (IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "RLC (IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "RLC (IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "RLC (IY+d)", 1, 0 },
    { "RLC (IY+d),A (UNDOCUMENTED)", 1, 0 },
    { "RRC (IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "RRC (IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "RRC (IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "RRC (IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "RRC (IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "RRC (IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "RRC (IY+d)", 1, 0 },
    { "RRC (IY+d),A (UNDOCUMENTED)", 1, 0 },

    { "RL (IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "RL (IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "RL (IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "RL (IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "RL (IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "RL (IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "RL (IY+d)", 1, 0 },
    { "RL (IY+d),A (UNDOCUMENTED)", 1, 0 },
    { "RR (IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "RR (IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "RR (IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "RR (IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "RR (IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "RR (IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "RR (IY+d)", 1, 0 },
    { "RR (IY+d),A (UNDOCUMENTED)", 1, 0 },

    { "SLA (IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "SLA (IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "SLA (IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "SLA (IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "SLA (IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "SLA (IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "SLA (IY+d)", 1, 0 },
    { "SLA (IY+d),A (UNDOCUMENTED)", 1, 0 },
    { "SRA (IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "SRA (IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "SRA (IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "SRA (IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "SRA (IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "SRA (IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "SRA (IY+d)", 1, 0 },
    { "SRA (IY+d),A (UNDOCUMENTED)", 1, 0 },

    { "SLL (IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "SLL (IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "SLL (IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "SLL (IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "SLL (IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "SLL (IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "SLL (IY+d) (UNDOCUMENTED)", 1, 0 },
    { "SLL (IY+d),A (UNDOCUMENTED)", 1, 0 },
    { "SRL (IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "SRL (IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "SRL (IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "SRL (IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "SRL (IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "SRL (IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "SRL (IY+d)", 1, 0 },
    { "SRL (IY+d),A (UNDOCUMENTED)", 1, 0 },

    { "BIT 0,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 0,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 0,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 0,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 0,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 0,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 0,(IY+d)", 1, 0 },
    { "BIT 0,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IY+d)", 1, 0 },
    { "BIT 1,(IY+d) (UNDOCUMENTED)", 1, 0 },

    { "BIT 2,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 2,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 2,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 2,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 2,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 2,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 2,(IY+d)", 1, 0 },
    { "BIT 2,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IY+d)", 1, 0 },
    { "BIT 3,(IY+d) (UNDOCUMENTED)", 1, 0 },

    { "BIT 4,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 4,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 4,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 4,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 4,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 4,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 4,(IY+d)", 1, 0 },
    { "BIT 4,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IY+d)", 1, 0 },
    { "BIT 5,(IY+d) (UNDOCUMENTED)", 1, 0 },

    { "BIT 6,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 6,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 6,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 6,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 6,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 6,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 6,(IY+d)", 1, 0 },
    { "BIT 6,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IY+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IY+d)", 1, 0 },
    { "BIT 7,(IY+d) (UNDOCUMENTED)", 1, 0 },

    { "RES 0,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 0,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 0,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 0,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 0,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 0,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 0,(IY+d)", 1, 0 },
    { "RES 0,(IY+d),A (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IY+d)", 1, 0 },
    { "RES 1,(IY+d),A (UNDOCUMENTED)", 1, 0 },

    { "RES 2,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 2,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 2,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 2,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 2,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 2,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 2,(IY+d)", 1, 0 },
    { "RES 2,(IY+d),A (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IY+d)", 1, 0 },
    { "RES 3,(IY+d),A (UNDOCUMENTED)", 1, 0 },

    { "RES 4,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 4,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 4,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 4,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 4,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 4,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 4,(IY+d)", 1, 0 },
    { "RES 4,(IY+d),A (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IY+d)", 1, 0 },
    { "RES 5,(IY+d),A (UNDOCUMENTED)", 1, 0 },

    { "RES 6,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 6,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 6,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 6,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 6,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 6,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 6,(IY+d)", 1, 0 },
    { "RES 6,(IY+d),A (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IY+d)", 1, 0 },
    { "RES 7,(IY+d),A (UNDOCUMENTED)", 1, 0 },

    { "SET 0,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 0,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 0,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 0,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 0,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 0,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 0,(IY+d)", 1, 0 },
    { "SET 0,(IY+d),A (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IY+d)", 1, 0 },
    { "SET 1,(IY+d),A (UNDOCUMENTED)", 1, 0 },

    { "SET 2,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 2,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 2,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 2,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 2,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 2,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 2,(IY+d)", 1, 0 },
    { "SET 2,(IY+d),A (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IY+d)", 1, 0 },
    { "SET 3,(IY+d),A (UNDOCUMENTED)", 1, 0 },

    { "SET 4,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 4,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 4,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 4,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 4,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 4,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 4,(IY+d)", 1, 0 },
    { "SET 4,(IY+d),A (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IY+d)", 1, 0 },
    { "SET 5,(IY+d),A (UNDOCUMENTED)", 1, 0 },

    { "SET 6,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 6,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 6,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 6,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 6,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 6,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 6,(IY+d)", 1, 0 },
    { "SET 6,(IY+d),A (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IY+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IY+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IY+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IY+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IY+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IY+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IY+d)", 1, 0 },
    { "SET 7,(IY+d),A (UNDOCUMENTED)", 1, 0 }
};

#endif	/* OPCODEFDCB_NAMES_H */

