/*
 * Gearsystem - Sega Master System / Game Gear Emulator
 * Copyright (C) 2013  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/ 
 * 
 */

#ifndef OPCODEED_NAMES_H
#define	OPCODEED_NAMES_H

static stOPCodeInfo kOPCodeEDNames[256] = {
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}IN {o}B,(C)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}OUT {o}(C),B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SBC {o}HL,BC", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}($%04X),BC", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}NEG", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RETN", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}IM {o}0", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}I,A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}IN {o}C,(C)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}OUT {o}(C),C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}ADC {o}HL,BC", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}BC,($%04X)", 4, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}NEG {e}[UNDOC]", "{n}NEG", "{n}NEG", "{n}NEG", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RETI", 2, GS_OPCode_Type_Implied),
    GS_OPCODE_SYNTAX("{n}IM {o}0 {e}[UNDOC]", "{n}IM {o}0", "{n}IM {o}0", "{n}IM {o}0", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}R,A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}IN {o}D,(C)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}OUT {o}(C),D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SBC {o}HL,DE", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}($%04X),DE", 4, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}NEG {e}[UNDOC]", "{n}NEG", "{n}NEG", "{n}NEG", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}RETN {e}[UNDOC]", "{n}RETN", "{n}RETN", "{n}RETN", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}IM {o}1", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}A,I", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}IN {o}E,(C)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}OUT {o}(C),E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}ADC {o}HL,DE", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}DE,($%04X)", 4, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}NEG {e}[UNDOC]", "{n}NEG", "{n}NEG", "{n}NEG", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}RETN {e}[UNDOC]", "{n}RETN", "{n}RETN", "{n}RETN", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}IM {o}2", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}A,R", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}IN {o}H,(C)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}OUT {o}(C),H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SBC {o}HL,HL", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}($%04X),HL", 4, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}NEG {e}[UNDOC]", "{n}NEG", "{n}NEG", "{n}NEG", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}RETN {e}[UNDOC]", "{n}RETN", "{n}RETN", "{n}RETN", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}IM {o}0 {e}[UNDOC]", "{n}IM {o}0", "{n}IM {o}0", "{n}IM {o}0", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RRD", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}IN {o}L,(C)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}OUT {o}(C),L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}ADC {o}HL,HL", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}HL,($%04X)", 4, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}NEG {e}[UNDOC]", "{n}NEG", "{n}NEG", "{n}NEG", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}RETN {e}[UNDOC]", "{n}RETN", "{n}RETN", "{n}RETN", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}IM {o}0 {e}[UNDOC]", "{n}IM {o}0", "{n}IM {o}0", "{n}IM {o}0", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RLD", 2, GS_OPCode_Type_Implied),

    GS_OPCODE_SYNTAX("{n}IN {o}F,(C) {e}[UNDOC]", "{n}IN {o}F,(C)", "{n}IN {o}F,(C)", "{n}IN {o}F,(C)", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}OUT {o}(C),0 {e}[UNDOC]", "{n}OUT {o}(C),0", "{n}OUT {o}(C),0", "{n}OUT {o}(C),0", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}SBC {o}HL,SP", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}($%04X),SP", 4, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}NEG {e}[UNDOC]", "{n}NEG", "{n}NEG", "{n}NEG", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}RETN {e}[UNDOC]", "{n}RETN", "{n}RETN", "{n}RETN", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}IM {o}1 {e}[UNDOC]", "{n}IM {o}1", "{n}IM {o}1", "{n}IM {o}1", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}IN {o}A,(C)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}OUT {o}(C),A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}ADC {o}HL,SP", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}SP,($%04X)", 4, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}NEG {e}[UNDOC]", "{n}NEG", "{n}NEG", "{n}NEG", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}RETN {e}[UNDOC]", "{n}RETN", "{n}RETN", "{n}RETN", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}IM {o}2 {e}[UNDOC]", "{n}IM {o}2", "{n}IM {o}2", "{n}IM {o}2", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}LDI", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}CPI", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}INI", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}OUTI", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LDD", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}CPD", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}IND", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}OUTD", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}LDIR", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}CPIR", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}INIR", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}OTIR", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LDDR", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}CPDR", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}INDR", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}OTDR", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INVALID", 2, GS_OPCode_Type_Data)
};

#endif	/* OPCODEED_NAMES_H */

