/*
 * Gearsystem - Sega Master System / Game Gear Emulator
 * Copyright (C) 2013  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/ 
 * 
 */

#ifndef OPCODEDD_NAMES_H
#define	OPCODEDD_NAMES_H

static stOPCodeInfo kOPCodeDDNames[256] = {
    { "NOP", 1, 0 },
    { "LD BC,nn", 1, 0 },
    { "LD (BC),A", 1, 0 },
    { "INC BC", 1, 0 },
    { "INC B", 1, 0 },
    { "DEC B", 1, 0 },
    { "LD B,n", 1, 0 },
    { "RLCA", 1, 0 },
    { "EX AF,AF'", 1, 0 },
    { "ADD IX,BC", 1, 0 },
    { "LD A,(BC)", 1, 0 },
    { "DEC BC", 1, 0 },
    { "INC C", 1, 0 },
    { "DEC C", 1, 0 },
    { "LD C,n", 1, 0 },
    { "RRCA", 1, 0 },

    { "DJNZ (PC+e)", 1, 0 },
    { "LD DE,nn", 1, 0 },
    { "LD (DE),A", 1, 0 },
    { "INC DE", 1, 0 },
    { "INC D", 1, 0 },
    { "DEC D", 1, 0 },
    { "LD D,n", 1, 0 },
    { "RLA", 1, 0 },
    { "JR n", 1, 0 },
    { "ADD IX,DE", 1, 0 },
    { "LD A,(DE)", 1, 0 },
    { "DEC DE", 1, 0 },
    { "INC E", 1, 0 },
    { "DEC E", 1, 0 },
    { "LD E,n", 1, 0 },
    { "RRA", 1, 0 },

    { "JR NZ,n", 1, 0 },
    { "LD IX,nn", 1, 0 },
    { "LD (nn),IX", 1, 0 },
    { "INC IX", 1, 0 },
    { "INC IXh (UNDOCUMENTED)", 1, 0 },
    { "DEC IXh (UNDOCUMENTED)", 1, 0 },
    { "LD IXh,n (UNDOCUMENTED)", 1, 0 },
    { "DAA", 1, 0 },
    { "JR Z,n", 1, 0 },
    { "ADD IX,IX", 1, 0 },
    { "LD IX,(nn)", 1, 0 },
    { "DEC IX", 1, 0 },
    { "INC IXl (UNDOCUMENTED)", 1, 0 },
    { "DEC IXl (UNDOCUMENTED)", 1, 0 },
    { "LD IXl,n (UNDOCUMENTED)", 1, 0 },
    { "CPL", 1, 0 },

    { "JR NC,n", 1, 0 },
    { "LD SP,nn", 1, 0 },
    { "LD (nn),A", 1, 0 },
    { "INC SP", 1, 0 },
    { "INC (IX+d)", 1, 0 },
    { "DEC (IX+d)", 1, 0 },
    { "LD (IX+d),n", 1, 0 },
    { "SCF", 1, 0 },
    { "JR C,n", 1, 0 },
    { "ADD IX,SP", 1, 0 },
    { "LD A,(nn)", 1, 0 },
    { "DEC SP", 1, 0 },
    { "INC A", 1, 0 },
    { "DEC A", 1, 0 },
    { "LDA,n", 1, 0 },
    { "CCF", 1, 0 },

    { "LD B,B", 1, 0 },
    { "LD B,C", 1, 0 },
    { "LD B,D", 1, 0 },
    { "LD B,E", 1, 0 },
    { "LD B,IXh (UNDOCUMENTED)", 1, 0 },
    { "LD B,IXl (UNDOCUMENTED)", 1, 0 },
    { "LD B,(IX+d)", 1, 0 },
    { "LD B,A", 1, 0 },
    { "LD C,B", 1, 0 },
    { "LD C,C", 1, 0 },
    { "LD C,D", 1, 0 },
    { "LD C,E", 1, 0 },
    { "LD C,IXh (UNDOCUMENTED)", 1, 0 },
    { "LD C,IXl (UNDOCUMENTED)", 1, 0 },
    { "LD C,(IX+d)", 1, 0 },
    { "LD C,A", 1, 0 },

    { "LD D,B", 1, 0 },
    { "LD D,C", 1, 0 },
    { "LD D,D", 1, 0 },
    { "LD D,E", 1, 0 },
    { "LD D,IXh (UNDOCUMENTED)", 1, 0 },
    { "LD D,IXl (UNDOCUMENTED)", 1, 0 },
    { "LD D,(IX+d)", 1, 0 },
    { "LD D,A", 1, 0 },
    { "LD E,B", 1, 0 },
    { "LD E,C", 1, 0 },
    { "LD E,D", 1, 0 },
    { "LD E,E", 1, 0 },
    { "LD E,IXh (UNDOCUMENTED)", 1, 0 },
    { "LD E,IXl (UNDOCUMENTED)", 1, 0 },
    { "LD E,(IX+d)", 1, 0 },
    { "LD E,A", 1, 0 },

    { "LD IXh,B (UNDOCUMENTED)", 1, 0 },
    { "LD IXh,C (UNDOCUMENTED)", 1, 0 },
    { "LD IXh,D (UNDOCUMENTED)", 1, 0 },
    { "LD IXh,E (UNDOCUMENTED)", 1, 0 },
    { "LD IXh,IXh (UNDOCUMENTED)", 1, 0 },
    { "LD IXh,IXl (UNDOCUMENTED)", 1, 0 },
    { "LD H,(IX+d)", 1, 0 },
    { "LD IXh,A (UNDOCUMENTED)", 1, 0 },
    { "LD IXl,B (UNDOCUMENTED)", 1, 0 },
    { "LD IXl,C (UNDOCUMENTED)", 1, 0 },
    { "LD IXl,D (UNDOCUMENTED)", 1, 0 },
    { "LD IXl,E (UNDOCUMENTED)", 1, 0 },
    { "LD IXl,IXh (UNDOCUMENTED)", 1, 0 },
    { "LD IXl,IXl (UNDOCUMENTED)", 1, 0 },
    { "LD L,(IX+d)", 1, 0 },
    { "LD IXl,A (UNDOCUMENTED)", 1, 0 },

    { "LD (IX+d),B", 1, 0 },
    { "LD (IX+d),C", 1, 0 },
    { "LD (IX+d),D", 1, 0 },
    { "LD (IX+d),E", 1, 0 },
    { "LD (IX+d),H", 1, 0 },
    { "LD (IX+d),L", 1, 0 },
    { "HALT", 1, 0 },
    { "LD (IX+d),A", 1, 0 },
    { "LD A,B", 1, 0 },
    { "LD A,C", 1, 0 },
    { "LD A,D", 1, 0 },
    { "LD A,E", 1, 0 },
    { "LD A,IXh (UNDOCUMENTED)", 1, 0 },
    { "LD A,IXl (UNDOCUMENTED)", 1, 0 },
    { "LD A,(IX+d)", 1, 0 },
    { "LD A,A", 1, 0 },

    { "ADD A,B", 1, 0 },
    { "ADD A,C", 1, 0 },
    { "ADD A,D", 1, 0 },
    { "ADD A,E", 1, 0 },
    { "ADD A,IXh (UNDOCUMENTED)", 1, 0 },
    { "ADD A,IXl (UNDOCUMENTED)", 1, 0 },
    { "ADD A,(IX+d)", 1, 0 },
    { "ADD A,A", 1, 0 },
    { "ADC A,B", 1, 0 },
    { "ADC A,C", 1, 0 },
    { "ADC A,D", 1, 0 },
    { "ADC A,E", 1, 0 },
    { "ADC A,IXh (UNDOCUMENTED)", 1, 0 },
    { "ADC A,IXl (UNDOCUMENTED)", 1, 0 },
    { "ADC A,(IX+d)", 1, 0 },
    { "ADC A,A", 1, 0 },

    { "SUB B", 1, 0 },
    { "SUB C", 1, 0 },
    { "SUB D", 1, 0 },
    { "SUB E", 1, 0 },
    { "SUB IXh (UNDOCUMENTED)", 1, 0 },
    { "SUB IXl (UNDOCUMENTED)", 1, 0 },
    { "SUB (IX+d)", 1, 0 },
    { "SUB A", 1, 0 },
    { "SBC A,B", 1, 0 },
    { "SBC A,C", 1, 0 },
    { "SBC A,D", 1, 0 },
    { "SBC A,E", 1, 0 },
    { "SBC A,IXh (UNDOCUMENTED)", 1, 0 },
    { "SBC A,IXl (UNDOCUMENTED)", 1, 0 },
    { "SBC A,(IX+d)", 1, 0 },
    { "SBC A,A", 1, 0 },

    { "AND B", 1, 0 },
    { "AND C", 1, 0 },
    { "AND D", 1, 0 },
    { "AND E", 1, 0 },
    { "AND IXh (UNDOCUMENTED)", 1, 0 },
    { "AND IXl (UNDOCUMENTED)", 1, 0 },
    { "AND (IX+d)", 1, 0 },
    { "AND A", 1, 0 },
    { "XOR B", 1, 0 },
    { "XOR C", 1, 0 },
    { "XOR D", 1, 0 },
    { "XOR E", 1, 0 },
    { "XOR IXh (UNDOCUMENTED)", 1, 0 },
    { "XOR IXl (UNDOCUMENTED)", 1, 0 },
    { "XOR (IX+d)", 1, 0 },
    { "XOR A", 1, 0 },

    { "OR B", 1, 0 },
    { "OR C", 1, 0 },
    { "OR D", 1, 0 },
    { "OR E", 1, 0 },
    { "OR IXh (UNDOCUMENTED)", 1, 0 },
    { "OR IXl (UNDOCUMENTED)", 1, 0 },
    { "OR (IX+d)", 1, 0 },
    { "OR A", 1, 0 },
    { "CP B", 1, 0 },
    { "CP C", 1, 0 },
    { "CP D", 1, 0 },
    { "CP E", 1, 0 },
    { "CP IXh (UNDOCUMENTED)", 1, 0 },
    { "CP IXl (UNDOCUMENTED)", 1, 0 },
    { "CP (IX+d)", 1, 0 },
    { "CP A", 1, 0 },

    { "RET NZ", 1, 0 },
    { "POP BC", 1, 0 },
    { "JP NZ,nn", 1, 0 },
    { "JP nn", 1, 0 },
    { "CALL NZ,nn", 1, 0 },
    { "PUSH BC", 1, 0 },
    { "ADD A,n", 1, 0 },
    { "RST ", 1, 0 },
    { "RET Z", 1, 0 },
    { "RET", 1, 0 },
    { "JP Z,nn", 1, 0 },
    { "CB PREFIX", 1, 0 },
    { "CALL Z,nn", 1, 0 },
    { "CALL nn", 1, 0 },
    { "ADC A,n", 1, 0 },
    { "RST 08H", 1, 0 },

    { "RET NC", 1, 0 },
    { "POP DE", 1, 0 },
    { "JP NC,nn", 1, 0 },
    { "OUT (n),A", 1, 0 },
    { "CALL NC,nn", 1, 0 },
    { "PUSH DE", 1, 0 },
    { "SUB n", 1, 0 },
    { "RST 10H", 1, 0 },
    { "RET C", 1, 0 },
    { "EXX", 1, 0 },
    { "JP C,nn", 1, 0 },
    { "IN A,(n)", 1, 0 },
    { "CALL C,nn", 1, 0 },
    { "DD PREFIX", 1, 0 },
    { "SBC A,n", 1, 0 },
    { "RST 18H", 1, 0 },

    { "RET PO", 1, 0 },
    { "POP IX", 1, 0 },
    { "JP PO,nn", 1, 0 },
    { "EX (SP),IX", 1, 0 },
    { "CALL PO,nn", 1, 0 },
    { "PUSH IX", 1, 0 },
    { "AND n", 1, 0 },
    { "RST 20H", 1, 0 },
    { "RET PE", 1, 0 },
    { "JP (IX)", 1, 0 },
    { "JP PE,nn", 1, 0 },
    { "EX DE,HL", 1, 0 },
    { "CALL PE,nn", 1, 0 },
    { "ED PREFIX", 1, 0 },
    { "XOR n", 1, 0 },
    { "RST 28H", 1, 0 },

    { "RET P", 1, 0 },
    { "POP AF", 1, 0 },
    { "JP P,nn", 1, 0 },
    { "DI", 1, 0 },
    { "CALL P,nn", 1, 0 },
    { "PUSH AF", 1, 0 },
    { "OR n", 1, 0 },
    { "RST 30H", 1, 0 },
    { "RET M", 1, 0 },
    { "LD SP,IX", 1, 0 },
    { "JP M,nn", 1, 0 },
    { "EI", 1, 0 },
    { "CALL M,nn", 1, 0 },
    { "FD PREFIX", 1, 0 },
    { "CP n", 1, 0 },
    { "RST 38H", 1, 0 }
};

#endif	/*OPCODEDD_NAMES_H */

