/*
 * Gearsystem - Sega Master System / Game Gear Emulator
 * Copyright (C) 2013  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/ 
 * 
 */

#ifndef OPCODEFDCB_NAMES_H
#define	OPCODEFDCB_NAMES_H

static stOPCodeInfo kOPCodeFDCBNames[256] = {
    { "{n}RLC {o}(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RLC {o}(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RLC {o}(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RLC {o}(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RLC {o}(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RLC {o}(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RLC {o}(IY%+d)", 4, 1 },
    { "{n}RLC {o}(IY%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IY%+d)", 4, 1 },
    { "{n}RRC {o}(IY%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}RL {o}(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RL {o}(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RL {o}(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RL {o}(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RL {o}(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RL {o}(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RL {o}(IY%+d)", 4, 1 },
    { "{n}RL {o}(IY%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IY%+d)", 4, 1 },
    { "{n}RR {o}(IY%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}SLA {o}(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SLA {o}(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SLA {o}(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SLA {o}(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SLA {o}(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SLA {o}(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SLA {o}(IY%+d)", 4, 1 },
    { "{n}SLA {o}(IY%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IY%+d)", 4, 1 },
    { "{n}SRA {o}(IY%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}SLL {o}(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IY%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IY%+d)", 4, 1 },
    { "{n}SRL {o}(IY%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}BIT {o}0,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}0,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}0,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}0,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}0,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}0,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}0,(IY%+d)", 4, 1 },
    { "{n}BIT {o}0,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IY%+d)", 4, 1 },
    { "{n}BIT {o}1,(IY%+d) {e}[UNDOC]", 4, 1 },

    { "{n}BIT {o}2,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}2,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}2,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}2,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}2,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}2,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}2,(IY%+d)", 4, 1 },
    { "{n}BIT {o}2,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IY%+d)", 4, 1 },
    { "{n}BIT {o}3,(IY%+d) {e}[UNDOC]", 4, 1 },

    { "{n}BIT {o}4,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}4,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}4,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}4,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}4,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}4,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}4,(IY%+d)", 4, 1 },
    { "{n}BIT {o}4,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IY%+d)", 4, 1 },
    { "{n}BIT {o}5,(IY%+d) {e}[UNDOC]", 4, 1 },

    { "{n}BIT {o}6,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}6,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}6,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}6,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}6,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}6,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}6,(IY%+d)", 4, 1 },
    { "{n}BIT {o}6,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IY%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IY%+d)", 4, 1 },
    { "{n}BIT {o}7,(IY%+d) {e}[UNDOC]", 4, 1 },

    { "{n}RES {o}0,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}0,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}0,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}0,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}0,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}0,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}0,(IY%+d)", 4, 1 },
    { "{n}RES {o}0,(IY%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IY%+d)", 4, 1 },
    { "{n}RES {o}1,(IY%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}RES {o}2,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}2,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}2,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}2,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}2,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}2,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}2,(IY%+d)", 4, 1 },
    { "{n}RES {o}2,(IY%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IY%+d)", 4, 1 },
    { "{n}RES {o}3,(IY%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}RES {o}4,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}4,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}4,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}4,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}4,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}4,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}4,(IY%+d)", 4, 1 },
    { "{n}RES {o}4,(IY%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IY%+d)", 4, 1 },
    { "{n}RES {o}5,(IY%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}RES {o}6,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}6,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}6,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}6,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}6,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}6,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}6,(IY%+d)", 4, 1 },
    { "{n}RES {o}6,(IY%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IY%+d)", 4, 1 },
    { "{n}RES {o}7,(IY%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}SET {o}0,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}0,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}0,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}0,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}0,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}0,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}0,(IY%+d)", 4, 1 },
    { "{n}SET {o}0,(IY%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IY%+d)", 4, 1 },
    { "{n}SET {o}1,(IY%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}SET {o}2,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}2,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}2,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}2,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}2,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}2,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}2,(IY%+d)", 4, 1 },
    { "{n}SET {o}2,(IY%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IY%+d)", 4, 1 },
    { "{n}SET {o}3,(IY%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}SET {o}4,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}4,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}4,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}4,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}4,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}4,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}4,(IY%+d)", 4, 1 },
    { "{n}SET {o}4,(IY%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IY%+d)", 4, 1 },
    { "{n}SET {o}5,(IY%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}SET {o}6,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}6,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}6,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}6,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}6,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}6,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}6,(IY%+d)", 4, 1 },
    { "{n}SET {o}6,(IY%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IY%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IY%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IY%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IY%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IY%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IY%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IY%+d)", 4, 1 },
    { "{n}SET {o}7,(IY%+d),A {e}[UNDOC]", 4, 1 }
};

#endif	/* OPCODEFDCB_NAMES_H */

