/*
 * Gearsystem - Sega Master System / Game Gear Emulator
 * Copyright (C) 2013  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/ 
 * 
 */

#ifndef OPCODECB_NAMES_H
#define	OPCODECB_NAMES_H

static stOPCodeInfo kOPCodeCBNames[256] = {
    GS_OPCODE("{n}RLC {o}B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RLC {o}C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RLC {o}D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RLC {o}E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RLC {o}H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RLC {o}L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RLC {o}(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RLC {o}A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RRC {o}B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RRC {o}C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RRC {o}D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RRC {o}E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RRC {o}H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RRC {o}L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RRC {o}(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RRC {o}A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}RL {o}B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RL {o}C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RL {o}D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RL {o}E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RL {o}H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RL {o}L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RL {o}(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RL {o}A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RR {o}B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RR {o}C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RR {o}D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RR {o}E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RR {o}H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RR {o}L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RR {o}(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RR {o}A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}SLA {o}B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SLA {o}C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SLA {o}D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SLA {o}E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SLA {o}H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SLA {o}L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SLA {o}(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SLA {o}A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRA {o}B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRA {o}C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRA {o}D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRA {o}E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRA {o}H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRA {o}L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRA {o}(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRA {o}A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE_SYNTAX("{n}SLL {o}B {e}[UNDOC]", "{n}SLL {o}B", "{n}SLL {o}B", "{n}SLL {o}B", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}SLL {o}C {e}[UNDOC]", "{n}SLL {o}C", "{n}SLL {o}C", "{n}SLL {o}C", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}SLL {o}D {e}[UNDOC]", "{n}SLL {o}D", "{n}SLL {o}D", "{n}SLL {o}D", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}SLL {o}E {e}[UNDOC]", "{n}SLL {o}E", "{n}SLL {o}E", "{n}SLL {o}E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}SLL {o}H {e}[UNDOC]", "{n}SLL {o}H", "{n}SLL {o}H", "{n}SLL {o}H", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}SLL {o}L {e}[UNDOC]", "{n}SLL {o}L", "{n}SLL {o}L", "{n}SLL {o}L", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}SLL {o}(HL) {e}[UNDOC]", "{n}SLL {o}(HL)", "{n}SLL {o}(HL)", "{n}SLL {o}(HL)", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}SLL {o}A {e}[UNDOC]", "{n}SLL {o}A", "{n}SLL {o}A", "{n}SLL {o}A", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}SRL {o}B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRL {o}C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRL {o}D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRL {o}E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRL {o}H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRL {o}L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRL {o}(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SRL {o}A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}BIT {o}0,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}0,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}0,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}0,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}0,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}0,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}0,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}0,A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}1,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}1,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}1,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}1,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}1,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}1,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}1,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}1,A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}BIT {o}2,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}2,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}2,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}2,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}2,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}2,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}2,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}2,A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}3,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}3,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}3,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}3,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}3,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}3,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}3,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}3,A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}BIT {o}4,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}4,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}4,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}4,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}4,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}4,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}4,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}4,A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}5,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}5,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}5,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}5,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}5,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}5,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}5,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}5,A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}BIT {o}6,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}6,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}6,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}6,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}6,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}6,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}6,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}6,A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}7,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}7,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}7,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}7,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}7,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}7,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}7,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}BIT {o}7,A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}RES {o}0,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}0,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}0,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}0,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}0,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}0,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}0,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}0,A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}1,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}1,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}1,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}1,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}1,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}1,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}1,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}1,A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}RES {o}2,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}2,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}2,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}2,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}2,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}2,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}2,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}2,A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}3,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}3,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}3,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}3,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}3,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}3,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}3,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}3,A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}RES {o}4,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}4,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}4,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}4,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}4,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}4,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}4,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}4,A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}5,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}5,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}5,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}5,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}5,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}5,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}5,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}5,A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}RES {o}6,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}6,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}6,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}6,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}6,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}6,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}6,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}6,A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}7,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}7,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}7,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}7,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}7,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}7,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}7,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}RES {o}7,A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}SET {o}0,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}0,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}0,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}0,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}0,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}0,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}0,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}0,A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}1,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}1,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}1,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}1,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}1,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}1,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}1,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}1,A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}SET {o}2,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}2,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}2,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}2,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}2,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}2,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}2,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}2,A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}3,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}3,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}3,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}3,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}3,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}3,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}3,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}3,A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}SET {o}4,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}4,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}4,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}4,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}4,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}4,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}4,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}4,A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}5,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}5,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}5,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}5,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}5,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}5,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}5,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}5,A", 2, GS_OPCode_Type_Implied),

    GS_OPCODE("{n}SET {o}6,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}6,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}6,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}6,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}6,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}6,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}6,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}6,A", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}7,B", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}7,C", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}7,D", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}7,E", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}7,H", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}7,L", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}7,(HL)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}SET {o}7,A", 2, GS_OPCode_Type_Implied)
};

#endif	/* OPCODECB_NAMES_H */

