/*
 * Gearsystem - Sega Master System / Game Gear Emulator
 * Copyright (C) 2013  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/ 
 * 
 */

#ifndef OPCODEDD_NAMES_H
#define	OPCODEDD_NAMES_H

static stOPCodeInfo kOPCodeDDNames[256] = {
    GS_OPCODE("{n}NOP", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}BC,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}(BC),A", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INC {o}BC", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INC {o}B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}DEC {o}B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}B,$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RLCA", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}EX {o}AF,AF'", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADD {o}IX,BC", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}A,(BC)", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}DEC {o}BC", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INC {o}C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}DEC {o}C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}C,$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RRCA", 2, GS_OPCode_Type_Data),

    GS_OPCODE_SYNTAX("{n}DJNZ {o}$%04X  {e}[%+d]", "{n}DJNZ {o}$%04X ", "{n}DJNZ {o}$%04X ", "{n}DJNZ {o}$%04X ", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}DE,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}(DE),A", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INC {o}DE", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INC {o}D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}DEC {o}D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}D,$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RLA", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}JR {o}$%04X  {e}[%+d]", "{n}JR {o}$%04X ", "{n}JR {o}$%04X ", "{n}JR {o}$%04X ", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADD {o}IX,DE", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}A,(DE)", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}DEC {o}DE", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INC {o}E", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}DEC {o}E", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}E,$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RRA", 2, GS_OPCode_Type_Data),

    GS_OPCODE_SYNTAX("{n}JR {o}NZ,$%04X  {e}[%+d]", "{n}JR {o}NZ,$%04X ", "{n}JR {o}NZ,$%04X ", "{n}JR {o}NZ,$%04X ", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}IX,$%04X", 4, GS_OPCode_Type_2b),
    GS_OPCODE("{n}LD {o}($%04X),IX", 4, GS_OPCode_Type_2b),
    GS_OPCODE("{n}INC {o}IX", 2, GS_OPCode_Type_Implied),
    GS_OPCODE_SYNTAX("{n}INC {o}IXh {e}[UNDOC]", "{n}INC {o}IXh", "{n}INC {o}IXh", "{n}INC {o}IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}DEC {o}IXh {e}[UNDOC]", "{n}DEC {o}IXh", "{n}DEC {o}IXh", "{n}DEC {o}IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}IXh,$%02X {e}[UNDOC]", "{n}LD {o}IXh,$%02X", "{n}LD {o}IXh,$%02X", "{n}LD {o}IXh,$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}DAA", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}JR {o}Z,$%04X  {e}[%+d]", "{n}JR {o}Z,$%04X ", "{n}JR {o}Z,$%04X ", "{n}JR {o}Z,$%04X ", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADD {o}IX,IX", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}IX,($%04X)", 4, GS_OPCode_Type_2b),
    GS_OPCODE("{n}DEC {o}IX", 2, GS_OPCode_Type_Implied),
    GS_OPCODE_SYNTAX("{n}INC {o}IXl {e}[UNDOC]", "{n}INC {o}IXl", "{n}INC {o}IXl", "{n}INC {o}IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}DEC {o}IXl {e}[UNDOC]", "{n}DEC {o}IXl", "{n}DEC {o}IXl", "{n}DEC {o}IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}IXl,$%02X {e}[UNDOC]", "{n}LD {o}IXl,$%02X", "{n}LD {o}IXl,$%02X", "{n}LD {o}IXl,$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CPL", 2, GS_OPCode_Type_Data),

    GS_OPCODE_SYNTAX("{n}JR {o}NC,$%04X  {e}[%+d]", "{n}JR {o}NC,$%04X ", "{n}JR {o}NC,$%04X ", "{n}JR {o}NC,$%04X ", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}SP,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}($%04X),A", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INC {o}SP", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INC {o}(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}DEC {o}(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}LD {o}(IX%+d),$%02X", 4, GS_OPCode_Type_Indexed_1b),
    GS_OPCODE("{n}SCF", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}JR {o}C,$%04X  {e}[%+d]", "{n}JR {o}C,$%04X ", "{n}JR {o}C,$%04X ", "{n}JR {o}C,$%04X ", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADD {o}IX,SP", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}LD {o}A,($%04X)", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}DEC {o}SP", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}INC {o}A", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}DEC {o}A", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}A,$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CCF", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}LD {o}B,B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}B,C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}B,D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}B,E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}B,IXh {e}[UNDOC]", "{n}LD {o}B,IXh", "{n}LD {o}B,IXh", "{n}LD {o}B,IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}B,IXl {e}[UNDOC]", "{n}LD {o}B,IXl", "{n}LD {o}B,IXl", "{n}LD {o}B,IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}B,(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}LD {o}B,A", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}C,B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}C,C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}C,D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}C,E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}C,IXh {e}[UNDOC]", "{n}LD {o}C,IXh", "{n}LD {o}C,IXh", "{n}LD {o}C,IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}C,IXl {e}[UNDOC]", "{n}LD {o}C,IXl", "{n}LD {o}C,IXl", "{n}LD {o}C,IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}C,(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}LD {o}C,A", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}LD {o}D,B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}D,C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}D,D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}D,E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}D,IXh {e}[UNDOC]", "{n}LD {o}D,IXh", "{n}LD {o}D,IXh", "{n}LD {o}D,IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}D,IXl {e}[UNDOC]", "{n}LD {o}D,IXl", "{n}LD {o}D,IXl", "{n}LD {o}D,IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}D,(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}LD {o}D,A", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}E,B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}E,C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}E,D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}E,E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}E,IXh {e}[UNDOC]", "{n}LD {o}E,IXh", "{n}LD {o}E,IXh", "{n}LD {o}E,IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}E,IXl {e}[UNDOC]", "{n}LD {o}E,IXl", "{n}LD {o}E,IXl", "{n}LD {o}E,IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}E,(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}LD {o}E,A", 2, GS_OPCode_Type_Data),

    GS_OPCODE_SYNTAX("{n}LD {o}IXh,B {e}[UNDOC]", "{n}LD {o}IXh,B", "{n}LD {o}IXh,B", "{n}LD {o}IXh,B", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}IXh,C {e}[UNDOC]", "{n}LD {o}IXh,C", "{n}LD {o}IXh,C", "{n}LD {o}IXh,C", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}IXh,D {e}[UNDOC]", "{n}LD {o}IXh,D", "{n}LD {o}IXh,D", "{n}LD {o}IXh,D", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}IXh,E {e}[UNDOC]", "{n}LD {o}IXh,E", "{n}LD {o}IXh,E", "{n}LD {o}IXh,E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}IXh,IXh {e}[UNDOC]", "{n}LD {o}IXh,IXh", "{n}LD {o}IXh,IXh", "{n}LD {o}IXh,IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}IXh,IXl {e}[UNDOC]", "{n}LD {o}IXh,IXl", "{n}LD {o}IXh,IXl", "{n}LD {o}IXh,IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}H,(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE_SYNTAX("{n}LD {o}IXh,A {e}[UNDOC]", "{n}LD {o}IXh,A", "{n}LD {o}IXh,A", "{n}LD {o}IXh,A", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}IXl,B {e}[UNDOC]", "{n}LD {o}IXl,B", "{n}LD {o}IXl,B", "{n}LD {o}IXl,B", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}IXl,C {e}[UNDOC]", "{n}LD {o}IXl,C", "{n}LD {o}IXl,C", "{n}LD {o}IXl,C", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}IXl,D {e}[UNDOC]", "{n}LD {o}IXl,D", "{n}LD {o}IXl,D", "{n}LD {o}IXl,D", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}IXl,E {e}[UNDOC]", "{n}LD {o}IXl,E", "{n}LD {o}IXl,E", "{n}LD {o}IXl,E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}IXl,IXh {e}[UNDOC]", "{n}LD {o}IXl,IXh", "{n}LD {o}IXl,IXh", "{n}LD {o}IXl,IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}IXl,IXl {e}[UNDOC]", "{n}LD {o}IXl,IXl", "{n}LD {o}IXl,IXl", "{n}LD {o}IXl,IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}L,(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE_SYNTAX("{n}LD {o}IXl,A {e}[UNDOC]", "{n}LD {o}IXl,A", "{n}LD {o}IXl,A", "{n}LD {o}IXl,A", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}LD {o}(IX%+d),B", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}LD {o}(IX%+d),C", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}LD {o}(IX%+d),D", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}LD {o}(IX%+d),E", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}LD {o}(IX%+d),H", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}LD {o}(IX%+d),L", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}HALT", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}(IX%+d),A", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}LD {o}A,B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}A,C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}A,D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}A,E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}A,IXh {e}[UNDOC]", "{n}LD {o}A,IXh", "{n}LD {o}A,IXh", "{n}LD {o}A,IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}LD {o}A,IXl {e}[UNDOC]", "{n}LD {o}A,IXl", "{n}LD {o}A,IXl", "{n}LD {o}A,IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}A,(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}LD {o}A,A", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}ADD {o}A,B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADD {o}A,C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADD {o}A,D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADD {o}A,E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}ADD {o}A,IXh {e}[UNDOC]", "{n}ADD {o}A,IXh", "{n}ADD {o}A,IXh", "{n}ADD {o}A,IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}ADD {o}A,IXl {e}[UNDOC]", "{n}ADD {o}A,IXl", "{n}ADD {o}A,IXl", "{n}ADD {o}A,IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADD {o}A,(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}ADD {o}A,A", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADC {o}A,B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADC {o}A,C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADC {o}A,D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADC {o}A,E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}ADC {o}A,IXh {e}[UNDOC]", "{n}ADC {o}A,IXh", "{n}ADC {o}A,IXh", "{n}ADC {o}A,IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}ADC {o}A,IXl {e}[UNDOC]", "{n}ADC {o}A,IXl", "{n}ADC {o}A,IXl", "{n}ADC {o}A,IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADC {o}A,(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}ADC {o}A,A", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}SUB {o}B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}SUB {o}C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}SUB {o}D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}SUB {o}E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}SUB {o}IXh {e}[UNDOC]", "{n}SUB {o}IXh", "{n}SUB {o}IXh", "{n}SUB {o}IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}SUB {o}IXl {e}[UNDOC]", "{n}SUB {o}IXl", "{n}SUB {o}IXl", "{n}SUB {o}IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}SUB {o}(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}SUB {o}A", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}SBC {o}A,B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}SBC {o}A,C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}SBC {o}A,D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}SBC {o}A,E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}SBC {o}A,IXh {e}[UNDOC]", "{n}SBC {o}A,IXh", "{n}SBC {o}A,IXh", "{n}SBC {o}A,IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}SBC {o}A,IXl {e}[UNDOC]", "{n}SBC {o}A,IXl", "{n}SBC {o}A,IXl", "{n}SBC {o}A,IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}SBC {o}A,(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}SBC {o}A,A", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}AND {o}B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}AND {o}C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}AND {o}D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}AND {o}E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}AND {o}IXh {e}[UNDOC]", "{n}AND {o}IXh", "{n}AND {o}IXh", "{n}AND {o}IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}AND {o}IXl {e}[UNDOC]", "{n}AND {o}IXl", "{n}AND {o}IXl", "{n}AND {o}IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}AND {o}(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}AND {o}A", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}XOR {o}B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}XOR {o}C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}XOR {o}D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}XOR {o}E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}XOR {o}IXh {e}[UNDOC]", "{n}XOR {o}IXh", "{n}XOR {o}IXh", "{n}XOR {o}IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}XOR {o}IXl {e}[UNDOC]", "{n}XOR {o}IXl", "{n}XOR {o}IXl", "{n}XOR {o}IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}XOR {o}(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}XOR {o}A", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}OR {o}B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}OR {o}C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}OR {o}D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}OR {o}E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}OR {o}IXh {e}[UNDOC]", "{n}OR {o}IXh", "{n}OR {o}IXh", "{n}OR {o}IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}OR {o}IXl {e}[UNDOC]", "{n}OR {o}IXl", "{n}OR {o}IXl", "{n}OR {o}IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}OR {o}(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}OR {o}A", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CP {o}B", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CP {o}C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CP {o}D", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CP {o}E", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}CP {o}IXh {e}[UNDOC]", "{n}CP {o}IXh", "{n}CP {o}IXh", "{n}CP {o}IXh", 2, GS_OPCode_Type_Data),
    GS_OPCODE_SYNTAX("{n}CP {o}IXl {e}[UNDOC]", "{n}CP {o}IXl", "{n}CP {o}IXl", "{n}CP {o}IXl", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CP {o}(IX%+d)", 3, GS_OPCode_Type_Indexed),
    GS_OPCODE("{n}CP {o}A", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}RET {o}NZ", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}POP {o}BC", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}JP {o}NZ,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}JP {o}$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CALL {o}NZ,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}PUSH {o}BC", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADD {o}A,$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RST {o}00H", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RET {o}Z", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RET", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}JP {o}Z,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CB {o}PREFIX", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CALL {o}Z,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CALL {o}$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ADC {o}A,$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RST {o}08H", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}RET {o}NC", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}POP {o}DE", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}JP {o}NC,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}OUT {o}($%02X),A", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CALL {o}NC,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}PUSH {o}DE", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}SUB {o}$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RST {o}10H", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RET {o}C", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}EXX", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}JP {o}C,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}IN {o}A,($%02X)", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CALL {o}C,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}DD {o}PREFIX", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}SBC {o}A,$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RST {o}18H", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}RET {o}PO", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}POP {o}IX", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}JP {o}PO,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}EX {o}(SP),IX", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}CALL {o}PO,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}PUSH {o}IX", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}AND {o}$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RST {o}20H", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RET {o}PE", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}JP {o}(IX)", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}JP {o}PE,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}EX {o}DE,HL", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CALL {o}PE,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}ED {o}PREFIX", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}XOR {o}$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RST {o}28H", 2, GS_OPCode_Type_Data),

    GS_OPCODE("{n}RET {o}P", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}POP {o}AF", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}JP {o}P,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}DI", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CALL {o}P,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}PUSH {o}AF", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}OR {o}$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RST {o}30H", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RET {o}M", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}LD {o}SP,IX", 2, GS_OPCode_Type_Implied),
    GS_OPCODE("{n}JP {o}M,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}EI", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CALL {o}M,$%04X", 4, GS_OPCode_Type_Data),
    GS_OPCODE("{n}FD {o}PREFIX", 2, GS_OPCode_Type_Data),
    GS_OPCODE("{n}CP {o}$%02X", 3, GS_OPCode_Type_Data),
    GS_OPCODE("{n}RST {o}38H", 2, GS_OPCode_Type_Data)
};

#endif	/*OPCODEDD_NAMES_H */

