/*
 * Gearsystem - Sega Master System / Game Gear Emulator
 * Copyright (C) 2013  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/ 
 * 
 */

#ifndef OPCODEDDCB_NAMES_H
#define	OPCODEDDCB_NAMES_H

static stOPCodeInfo kOPCodeDDCBNames[256] = {
    { "RLC (IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "RLC (IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "RLC (IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "RLC (IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "RLC (IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "RLC (IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "RLC (IX+d)", 1, 0 },
    { "RLC (IX+d),A (UNDOCUMENTED)", 1, 0 },
    { "RRC (IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "RRC (IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "RRC (IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "RRC (IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "RRC (IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "RRC (IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "RRC (IX+d)", 1, 0 },
    { "RRC (IX+d),A (UNDOCUMENTED)", 1, 0 },

    { "RL (IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "RL (IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "RL (IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "RL (IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "RL (IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "RL (IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "RL (IX+d)", 1, 0 },
    { "RL (IX+d),A (UNDOCUMENTED)", 1, 0 },
    { "RR (IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "RR (IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "RR (IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "RR (IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "RR (IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "RR (IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "RR (IX+d)", 1, 0 },
    { "RR (IX+d),A (UNDOCUMENTED)", 1, 0 },

    { "SLA (IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "SLA (IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "SLA (IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "SLA (IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "SLA (IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "SLA (IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "SLA (IX+d)", 1, 0 },
    { "SLA (IX+d),A (UNDOCUMENTED)", 1, 0 },
    { "SRA (IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "SRA (IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "SRA (IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "SRA (IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "SRA (IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "SRA (IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "SRA (IX+d)", 1, 0 },
    { "SRA (IX+d),A (UNDOCUMENTED)", 1, 0 },

    { "SLL (IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "SLL (IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "SLL (IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "SLL (IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "SLL (IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "SLL (IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "SLL (IX+d) (UNDOCUMENTED)", 1, 0 },
    { "SLL (IX+d),A (UNDOCUMENTED)", 1, 0 },
    { "SRL (IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "SRL (IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "SRL (IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "SRL (IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "SRL (IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "SRL (IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "SRL (IX+d)", 1, 0 },
    { "SRL (IX+d),A (UNDOCUMENTED)", 1, 0 },

    { "BIT 0,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 0,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 0,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 0,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 0,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 0,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 0,(IX+d)", 1, 0 },
    { "BIT 0,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 1,(IX+d)", 1, 0 },
    { "BIT 1,(IX+d) (UNDOCUMENTED)", 1, 0 },

    { "BIT 2,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 2,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 2,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 2,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 2,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 2,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 2,(IX+d)", 1, 0 },
    { "BIT 2,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 3,(IX+d)", 1, 0 },
    { "BIT 3,(IX+d) (UNDOCUMENTED)", 1, 0 },

    { "BIT 4,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 4,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 4,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 4,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 4,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 4,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 4,(IX+d)", 1, 0 },
    { "BIT 4,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 5,(IX+d)", 1, 0 },
    { "BIT 5,(IX+d) (UNDOCUMENTED)", 1, 0 },

    { "BIT 6,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 6,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 6,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 6,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 6,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 6,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 6,(IX+d)", 1, 0 },
    { "BIT 6,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IX+d) (UNDOCUMENTED)", 1, 0 },
    { "BIT 7,(IX+d)", 1, 0 },
    { "BIT 7,(IX+d) (UNDOCUMENTED)", 1, 0 },

    { "RES 0,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 0,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 0,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 0,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 0,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 0,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 0,(IX+d)", 1, 0 },
    { "RES 0,(IX+d),A (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 1,(IX+d)", 1, 0 },
    { "RES 1,(IX+d),A (UNDOCUMENTED)", 1, 0 },

    { "RES 2,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 2,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 2,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 2,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 2,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 2,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 2,(IX+d)", 1, 0 },
    { "RES 2,(IX+d),A (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 3,(IX+d)", 1, 0 },
    { "RES 3,(IX+d),A (UNDOCUMENTED)", 1, 0 },

    { "RES 4,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 4,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 4,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 4,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 4,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 4,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 4,(IX+d)", 1, 0 },
    { "RES 4,(IX+d),A (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 5,(IX+d)", 1, 0 },
    { "RES 5,(IX+d),A (UNDOCUMENTED)", 1, 0 },

    { "RES 6,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 6,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 6,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 6,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 6,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 6,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 6,(IX+d)", 1, 0 },
    { "RES 6,(IX+d),A (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "RES 7,(IX+d)", 1, 0 },
    { "RES 7,(IX+d),A (UNDOCUMENTED)", 1, 0 },

    { "SET 0,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 0,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 0,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 0,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 0,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 0,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 0,(IX+d)", 1, 0 },
    { "SET 0,(IX+d),A (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 1,(IX+d)", 1, 0 },
    { "SET 1,(IX+d),A (UNDOCUMENTED)", 1, 0 },

    { "SET 2,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 2,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 2,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 2,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 2,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 2,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 2,(IX+d)", 1, 0 },
    { "SET 2,(IX+d),A (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 3,(IX+d)", 1, 0 },
    { "SET 3,(IX+d),A (UNDOCUMENTED)", 1, 0 },

    { "SET 4,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 4,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 4,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 4,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 4,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 4,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 4,(IX+d)", 1, 0 },
    { "SET 4,(IX+d),A (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 5,(IX+d)", 1, 0 },
    { "SET 5,(IX+d),A (UNDOCUMENTED)", 1, 0 },

    { "SET 6,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 6,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 6,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 6,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 6,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 6,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 6,(IX+d)", 1, 0 },
    { "SET 6,(IX+d),A (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IX+d),B (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IX+d),C (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IX+d),D (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IX+d),E (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IX+d),H (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IX+d),L (UNDOCUMENTED)", 1, 0 },
    { "SET 7,(IX+d)", 1, 0 },
    { "SET 7,(IX+d),A (UNDOCUMENTED)", 1, 0 }
};

#endif	/* OPCODEDDCB_NAMES_H */
