/*
 * Gearsystem - Sega Master System / Game Gear Emulator
 * Copyright (C) 2013  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/ 
 * 
 */

#ifndef OPCODEDDCB_NAMES_H
#define	OPCODEDDCB_NAMES_H

static stOPCodeInfo kOPCodeDDCBNames[256] = {
    { "{n}RLC {o}(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RLC {o}(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RLC {o}(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RLC {o}(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RLC {o}(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RLC {o}(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RLC {o}(IX%+d)", 4, 1 },
    { "{n}RLC {o}(IX%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RRC {o}(IX%+d)", 4, 1 },
    { "{n}RRC {o}(IX%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}RL {o}(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RL {o}(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RL {o}(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RL {o}(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RL {o}(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RL {o}(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RL {o}(IX%+d)", 4, 1 },
    { "{n}RL {o}(IX%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RR {o}(IX%+d)", 4, 1 },
    { "{n}RR {o}(IX%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}SLA {o}(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SLA {o}(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SLA {o}(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SLA {o}(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SLA {o}(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SLA {o}(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SLA {o}(IX%+d)", 4, 1 },
    { "{n}SLA {o}(IX%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SRA {o}(IX%+d)", 4, 1 },
    { "{n}SRA {o}(IX%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}SLL {o}(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}SLL {o}(IX%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SRL {o}(IX%+d)", 4, 1 },
    { "{n}SRL {o}(IX%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}BIT {o}0,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}0,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}0,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}0,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}0,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}0,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}0,(IX%+d)", 4, 1 },
    { "{n}BIT {o}0,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}1,(IX%+d)", 4, 1 },
    { "{n}BIT {o}1,(IX%+d) {e}[UNDOC]", 4, 1 },

    { "{n}BIT {o}2,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}2,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}2,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}2,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}2,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}2,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}2,(IX%+d)", 4, 1 },
    { "{n}BIT {o}2,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}3,(IX%+d)", 4, 1 },
    { "{n}BIT {o}3,(IX%+d) {e}[UNDOC]", 4, 1 },

    { "{n}BIT {o}4,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}4,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}4,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}4,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}4,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}4,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}4,(IX%+d)", 4, 1 },
    { "{n}BIT {o}4,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}5,(IX%+d)", 4, 1 },
    { "{n}BIT {o}5,(IX%+d) {e}[UNDOC]", 4, 1 },

    { "{n}BIT {o}6,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}6,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}6,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}6,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}6,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}6,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}6,(IX%+d)", 4, 1 },
    { "{n}BIT {o}6,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IX%+d) {e}[UNDOC]", 4, 1 },
    { "{n}BIT {o}7,(IX%+d)", 4, 1 },
    { "{n}BIT {o}7,(IX%+d) {e}[UNDOC]", 4, 1 },

    { "{n}RES {o}0,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}0,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}0,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}0,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}0,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}0,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}0,(IX%+d)", 4, 1 },
    { "{n}RES {o}0,(IX%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}1,(IX%+d)", 4, 1 },
    { "{n}RES {o}1,(IX%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}RES {o}2,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}2,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}2,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}2,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}2,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}2,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}2,(IX%+d)", 4, 1 },
    { "{n}RES {o}2,(IX%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}3,(IX%+d)", 4, 1 },
    { "{n}RES {o}3,(IX%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}RES {o}4,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}4,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}4,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}4,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}4,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}4,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}4,(IX%+d)", 4, 1 },
    { "{n}RES {o}4,(IX%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}5,(IX%+d)", 4, 1 },
    { "{n}RES {o}5,(IX%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}RES {o}6,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}6,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}6,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}6,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}6,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}6,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}6,(IX%+d)", 4, 1 },
    { "{n}RES {o}6,(IX%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}RES {o}7,(IX%+d)", 4, 1 },
    { "{n}RES {o}7,(IX%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}SET {o}0,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}0,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}0,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}0,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}0,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}0,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}0,(IX%+d)", 4, 1 },
    { "{n}SET {o}0,(IX%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}1,(IX%+d)", 4, 1 },
    { "{n}SET {o}1,(IX%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}SET {o}2,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}2,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}2,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}2,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}2,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}2,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}2,(IX%+d)", 4, 1 },
    { "{n}SET {o}2,(IX%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}3,(IX%+d)", 4, 1 },
    { "{n}SET {o}3,(IX%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}SET {o}4,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}4,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}4,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}4,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}4,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}4,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}4,(IX%+d)", 4, 1 },
    { "{n}SET {o}4,(IX%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}5,(IX%+d)", 4, 1 },
    { "{n}SET {o}5,(IX%+d),A {e}[UNDOC]", 4, 1 },

    { "{n}SET {o}6,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}6,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}6,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}6,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}6,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}6,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}6,(IX%+d)", 4, 1 },
    { "{n}SET {o}6,(IX%+d),A {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IX%+d),B {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IX%+d),C {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IX%+d),D {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IX%+d),E {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IX%+d),H {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IX%+d),L {e}[UNDOC]", 4, 1 },
    { "{n}SET {o}7,(IX%+d)", 4, 1 },
    { "{n}SET {o}7,(IX%+d),A {e}[UNDOC]", 4, 1 }
};

#endif	/* OPCODEDDCB_NAMES_H */
