/*
 * Gearsystem - Sega Master System / Game Gear Emulator
 * Copyright (C) 2013  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/ 
 * 
 */

#ifndef OPCODEFD_NAMES_H
#define	OPCODEFD_NAMES_H

static stOPCodeInfo kOPCodeFDNames[256] = {
    { "{n}NOP", 2, 0 },
    { "{n}LD {o}BC,$%04X", 4, 3 },
    { "{n}LD {o}(BC),A", 2, 0 },
    { "{n}INC {o}BC", 2, 0 },
    { "{n}INC {o}B", 2, 0 },
    { "{n}DEC {o}B", 2, 0 },
    { "{n}LD {o}B,$%02X", 3, 2 },
    { "{n}RLCA", 2, 0 },
    { "{n}EX {o}AF,AF'", 2, 0 },
    { "{n}ADD {o}IY,BC", 2, 0 },
    { "{n}LD {o}A,(BC)", 2, 0 },
    { "{n}DEC {o}BC", 2, 0 },
    { "{n}INC {o}C", 2, 0 },
    { "{n}DEC {o}C", 2, 0 },
    { "{n}LD {o}C,$%02X", 3, 2 },
    { "{n}RRCA", 2, 0 },

    { "{n}DJNZ {o}$%04X  {e}[%+d]", 3, 5 },
    { "{n}LD {o}DE,$%04X", 4, 3 },
    { "{n}LD {o}(DE),A", 2, 0 },
    { "{n}INC {o}DE", 2, 0 },
    { "{n}INC {o}D", 2, 0 },
    { "{n}DEC {o}D", 2, 0 },
    { "{n}LD {o}D,$%02X", 3, 2 },
    { "{n}RLA", 2, 0 },
    { "{n}JR {o}$%04X  {e}[%+d]", 3, 5 },
    { "{n}ADD {o}IY,DE", 2, 0 },
    { "{n}LD {o}A,(DE)", 2, 0 },
    { "{n}DEC {o}DE", 2, 0 },
    { "{n}INC {o}E", 2, 0 },
    { "{n}DEC {o}E", 2, 0 },
    { "{n}LD {o}E,$%02X", 3, 2 },
    { "{n}RRA", 2, 0 },

    { "{n}JR {o}NZ,$%04X  {e}[%+d]", 3, 5 },
    { "{n}LD {o}IY,$%04X", 4, 3 },
    { "{n}LD {o}($%04X),IY", 4, 3 },
    { "{n}INC {o}IY", 2, 0 },
    { "{n}INC {o}IYh {e}[UNDOC]", 2, 0 },
    { "{n}DEC {o}IYh {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}IYh,$%02X {e}[UNDOC]", 3, 2 },
    { "{n}DAA", 2, 0 },
    { "{n}JR {o}Z,$%04X  {e}[%+d]", 3, 5 },
    { "{n}ADD {o}IY,IY", 2, 0 },
    { "{n}LD {o}IY,($%04X)", 4, 3 },
    { "{n}DEC {o}IY", 2, 0 },
    { "{n}INC {o}IYl {e}[UNDOC]", 2, 0 },
    { "{n}DEC {o}IYl {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}IYl,$%02X {e}[UNDOC]", 3, 2 },
    { "{n}CPL", 2, 0 },

    { "{n}JR {o}NC,$%04X  {e}[%+d]", 3, 5 },
    { "{n}LD {o}SP,$%04X", 4, 3 },
    { "{n}LD {o}($%04X),A", 4, 3 },
    { "{n}INC {o}SP", 2, 0 },
    { "{n}INC {o}(IY%+d)", 3, 4 },
    { "{n}DEC {o}(IY%+d)", 3, 4 },
    { "{n}LD {o}(IY%+d),$%02X", 4, 6 },
    { "{n}SCF", 2, 0 },
    { "{n}JR {o}C,$%04X  {e}[%+d]", 3, 5 },
    { "{n}ADD {o}IY,SP", 2, 0 },
    { "{n}LD {o}A,($%04X)", 4, 3 },
    { "{n}DEC {o}SP", 2, 0 },
    { "{n}INC {o}A", 2, 0 },
    { "{n}DEC {o}A", 2, 0 },
    { "{n}LD {o}A,$%02X", 3, 2 },
    { "{n}CCF", 2, 0 },

    { "{n}LD {o}B,B", 2, 0 },
    { "{n}LD {o}B,C", 2, 0 },
    { "{n}LD {o}B,D", 2, 0 },
    { "{n}LD {o}B,E", 2, 0 },
    { "{n}LD {o}B,IYh {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}B,IYl {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}B,(IY%+d)", 3, 4 },
    { "{n}LD {o}B,A", 2, 0 },
    { "{n}LD {o}C,B", 2, 0 },
    { "{n}LD {o}C,C", 2, 0 },
    { "{n}LD {o}C,D", 2, 0 },
    { "{n}LD {o}C,E", 2, 0 },
    { "{n}LD {o}C,IYh {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}C,IYl {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}C,(IY%+d)", 3, 4 },
    { "{n}LD {o}C,A", 2, 0 },

    { "{n}LD {o}D,B", 2, 0 },
    { "{n}LD {o}D,C", 2, 0 },
    { "{n}LD {o}D,D", 2, 0 },
    { "{n}LD {o}D,E", 2, 0 },
    { "{n}LD {o}D,IYh {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}D,IYl {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}D,(IY%+d)", 3, 4 },
    { "{n}LD {o}D,A", 2, 0 },
    { "{n}LD {o}E,B", 2, 0 },
    { "{n}LD {o}E,C", 2, 0 },
    { "{n}LD {o}E,D", 2, 0 },
    { "{n}LD {o}E,E", 2, 0 },
    { "{n}LD {o}E,IYh {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}E,IYl {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}E,(IY%+d)", 3, 4 },
    { "{n}LD {o}E,A", 2, 0 },

    { "{n}LD {o}IYh,B {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}IYh,C {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}IYh,D {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}IYh,E {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}IYh,IYh {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}IYh,IYl {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}H,(IY%+d)", 3, 4 },
    { "{n}LD {o}IYh,A {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}IYl,B {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}IYl,C {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}IYl,D {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}IYl,E {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}IYl,IYh {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}IYl,IYl {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}L,(IY%+d)", 3, 4 },
    { "{n}LD {o}IYl,A {e}[UNDOC]", 2, 0 },

    { "{n}LD {o}(IY%+d),B", 3, 4 },
    { "{n}LD {o}(IY%+d),C", 3, 4 },
    { "{n}LD {o}(IY%+d),D", 3, 4 },
    { "{n}LD {o}(IY%+d),E", 3, 4 },
    { "{n}LD {o}(IY%+d),H", 3, 4 },
    { "{n}LD {o}(IY%+d),L", 3, 4 },
    { "{n}HALT", 2, 0 },
    { "{n}LD {o}(IY%+d),A", 3, 4 },
    { "{n}LD {o}A,B", 2, 0 },
    { "{n}LD {o}A,C", 2, 0 },
    { "{n}LD {o}A,D", 2, 0 },
    { "{n}LD {o}A,E", 2, 0 },
    { "{n}LD {o}A,IYh {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}A,IYl {e}[UNDOC]", 2, 0 },
    { "{n}LD {o}A,(IY%+d)", 3, 4 },
    { "{n}LD {o}A,A", 2, 0 },

    { "{n}ADD {o}A,B", 2, 0 },
    { "{n}ADD {o}A,C", 2, 0 },
    { "{n}ADD {o}A,D", 2, 0 },
    { "{n}ADD {o}A,E", 2, 0 },
    { "{n}ADD {o}A,IYh {e}[UNDOC]", 2, 0 },
    { "{n}ADD {o}A,IYl {e}[UNDOC]", 2, 0 },
    { "{n}ADD {o}A,(IY%+d)", 3, 4 },
    { "{n}ADD {o}A,A", 2, 0 },
    { "{n}ADC {o}A,B", 2, 0 },
    { "{n}ADC {o}A,C", 2, 0 },
    { "{n}ADC {o}A,D", 2, 0 },
    { "{n}ADC {o}A,E", 2, 0 },
    { "{n}ADC {o}A,IYh {e}[UNDOC]", 2, 0 },
    { "{n}ADC {o}A,IYl {e}[UNDOC]", 2, 0 },
    { "{n}ADC {o}A,(IY%+d)", 3, 4 },
    { "{n}ADC {o}A,A", 2, 0 },

    { "{n}SUB {o}B", 2, 0 },
    { "{n}SUB {o}C", 2, 0 },
    { "{n}SUB {o}D", 2, 0 },
    { "{n}SUB {o}E", 2, 0 },
    { "{n}SUB {o}IYh {e}[UNDOC]", 2, 0 },
    { "{n}SUB {o}IYl {e}[UNDOC]", 2, 0 },
    { "{n}SUB {o}(IY%+d)", 3, 4 },
    { "{n}SUB {o}A", 2, 0 },
    { "{n}SBC {o}A,B", 2, 0 },
    { "{n}SBC {o}A,C", 2, 0 },
    { "{n}SBC {o}A,D", 2, 0 },
    { "{n}SBC {o}A,E", 2, 0 },
    { "{n}SBC {o}A,IYh {e}[UNDOC]", 2, 0 },
    { "{n}SBC {o}A,IYl {e}[UNDOC]", 2, 0 },
    { "{n}SBC {o}A,(IY%+d)", 3, 4 },
    { "{n}SBC {o}A,A", 2, 0 },

    { "{n}AND {o}B", 2, 0 },
    { "{n}AND {o}C", 2, 0 },
    { "{n}AND {o}D", 2, 0 },
    { "{n}AND {o}E", 2, 0 },
    { "{n}AND {o}IYh {e}[UNDOC]", 2, 0 },
    { "{n}AND {o}IYl {e}[UNDOC]", 2, 0 },
    { "{n}AND {o}(IY%+d)", 3, 4 },
    { "{n}AND {o}A", 2, 0 },
    { "{n}XOR {o}B", 2, 0 },
    { "{n}XOR {o}C", 2, 0 },
    { "{n}XOR {o}D", 2, 0 },
    { "{n}XOR {o}E", 2, 0 },
    { "{n}XOR {o}IYh {e}[UNDOC]", 2, 0 },
    { "{n}XOR {o}IYl {e}[UNDOC]", 2, 0 },
    { "{n}XOR {o}(IY%+d)", 3, 4 },
    { "{n}XOR {o}A", 2, 0 },

    { "{n}OR {o}B", 2, 0 },
    { "{n}OR {o}C", 2, 0 },
    { "{n}OR {o}D", 2, 0 },
    { "{n}OR {o}E", 2, 0 },
    { "{n}OR {o}IYh {e}[UNDOC]", 2, 0 },
    { "{n}OR {o}IYl {e}[UNDOC]", 2, 0 },
    { "{n}OR {o}(IY%+d)", 3, 4 },
    { "{n}OR {o}A", 2, 0 },
    { "{n}CP {o}B", 2, 0 },
    { "{n}CP {o}C", 2, 0 },
    { "{n}CP {o}D", 2, 0 },
    { "{n}CP {o}E", 2, 0 },
    { "{n}CP {o}IYh {e}[UNDOC]", 2, 0 },
    { "{n}CP {o}IYl {e}[UNDOC]", 2, 0 },
    { "{n}CP {o}(IY%+d)", 3, 4 },
    { "{n}CP {o}A", 2, 0 },

    { "{n}RET {o}NZ", 2, 0 },
    { "{n}POP {o}BC", 2, 0 },
    { "{n}JP {o}NZ,$%04X", 4, 3 },
    { "{n}JP {o}$%04X", 4, 3 },
    { "{n}CALL {o}NZ,$%04X", 4, 3 },
    { "{n}PUSH {o}BC", 2, 0 },
    { "{n}ADD {o}A,$%02X", 3, 2 },
    { "{n}RST {o}00H", 2, 0 },
    { "{n}RET {o}Z", 2, 0 },
    { "{n}RET", 2, 0 },
    { "{n}JP {o}Z,$%04X", 4, 3 },
    { "{n}CB {o}PREFIX", 2, 0 },
    { "{n}CALL {o}Z,$%04X", 4, 3 },
    { "{n}CALL {o}$%04X", 4, 3 },
    { "{n}ADC {o}A,$%02X", 3, 2 },
    { "{n}RST {o}08H", 2, 0 },

    { "{n}RET {o}NC", 2, 0 },
    { "{n}POP {o}DE", 2, 0 },
    { "{n}JP {o}NC,$%04X", 4, 3 },
    { "{n}OUT {o}($%02X),A", 3, 2 },
    { "{n}CALL {o}NC,$%04X", 4, 3 },
    { "{n}PUSH {o}DE", 2, 0 },
    { "{n}SUB {o}$%02X", 3, 2 },
    { "{n}RST {o}10H", 2, 0 },
    { "{n}RET {o}C", 2, 0 },
    { "{n}EXX", 2, 0 },
    { "{n}JP {o}C,$%04X", 4, 3 },
    { "{n}IN {o}A,($%02X)", 3, 2 },
    { "{n}CALL {o}C,$%04X", 4, 3 },
    { "{n}DD {o}PREFIX", 2, 0 },
    { "{n}SBC {o}A,$%02X", 3, 2 },
    { "{n}RST {o}18H", 2, 0 },

    { "{n}RET {o}PO", 2, 0 },
    { "{n}POP {o}IY", 2, 0 },
    { "{n}JP {o}PO,$%04X", 4, 3 },
    { "{n}EX {o}(SP),IY", 2, 0 },
    { "{n}CALL {o}PO,$%04X", 4, 3 },
    { "{n}PUSH {o}IY", 2, 0 },
    { "{n}AND {o}$%02X", 3, 2 },
    { "{n}RST {o}20H", 2, 0 },
    { "{n}RET {o}PE", 2, 0 },
    { "{n}JP {o}(IY)", 2, 0 },
    { "{n}JP {o}PE,$%04X", 4, 3 },
    { "{n}EX {o}DE,HL", 2, 0 },
    { "{n}CALL {o}PE,$%04X", 4, 3 },
    { "{n}ED {o}PREFIX", 2, 0 },
    { "{n}XOR {o}$%02X", 3, 2 },
    { "{n}RST {o}28H", 2, 0 },

    { "{n}RET {o}P", 2, 0 },
    { "{n}POP {o}AF", 2, 0 },
    { "{n}JP {o}P,$%04X", 4, 3 },
    { "{n}DI", 2, 0 },
    { "{n}CALL {o}P,$%04X", 4, 3 },
    { "{n}PUSH {o}AF", 2, 0 },
    { "{n}OR {o}$%02X", 3, 2 },
    { "{n}RST {o}30H", 2, 0 },
    { "{n}RET {o}M", 2, 0 },
    { "{n}LD {o}SP,IY", 2, 0 },
    { "{n}JP {o}M,$%04X", 4, 3 },
    { "{n}EI", 2, 0 },
    { "{n}CALL {o}M,$%04X", 4, 3 },
    { "{n}FD {o}PREFIX", 2, 0 },
    { "{n}CP {o}$%02X", 3, 2 },
    { "{n}RST {o}38H", 2, 0 }
};

#endif	/* OPCODEFD_NAMES_H */

