/*
 * Gearsystem - Sega Master System / Game Gear Emulator
 * Copyright (C) 2013  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/ 
 * 
 */

#ifndef OPCODEXX_NAMES_H
#define	OPCODEXX_NAMES_H

static stOPCodeInfo kOPCodeNames[256] = {
    { "{n}NOP", 1, 0 },
    { "{n}LD {o}BC,$%04X", 3, 3 },
    { "{n}LD {o}(BC),A", 1, 0 },
    { "{n}INC {o}BC", 1, 0 },
    { "{n}INC {o}B", 1, 0 },
    { "{n}DEC {o}B", 1, 0 },
    { "{n}LD {o}B,$%02X", 2, 2 },
    { "{n}RLCA", 1, 0 },
    { "{n}EX {o}AF,AF'", 1, 0 },
    { "{n}ADD {o}HL,BC", 1, 0 },
    { "{n}LD {o}A,(BC)", 1, 0 },
    { "{n}DEC {o}BC", 1, 0 },
    { "{n}INC {o}C", 1, 0 },
    { "{n}DEC {o}C", 1, 0 },
    { "{n}LD {o}C,$%02X", 2, 2 },
    { "{n}RRCA", 1, 0 },

    { "{n}DJNZ {o}$%04X  {e}[%+d]", 2, 5 },
    { "{n}LD {o}DE,$%04X", 3, 3 },
    { "{n}LD {o}(DE),A", 1, 0 },
    { "{n}INC {o}DE", 1, 0 },
    { "{n}INC {o}D", 1, 0 },
    { "{n}DEC {o}D", 1, 0 },
    { "{n}LD {o}D,$%02X", 2, 2 },
    { "{n}RLA", 1, 0 },
    { "{n}JR {o}$%04X  {e}[%+d]", 2, 5 },
    { "{n}ADD {o}HL,DE", 1, 0 },
    { "{n}LD {o}A,(DE)", 1, 0 },
    { "{n}DEC {o}DE", 1, 0 },
    { "{n}INC {o}E", 1, 0 },
    { "{n}DEC {o}E", 1, 0 },
    { "{n}LD {o}E,$%02X", 2, 2 },
    { "{n}RRA", 1, 0 },

    { "{n}JR {o}NZ,$%04X  {e}[%+d]", 2, 5 },
    { "{n}LD {o}HL,$%04X", 3, 3 },
    { "{n}LD {o}($%04X),HL", 3, 3 },
    { "{n}INC {o}HL", 1, 0 },
    { "{n}INC {o}H", 1, 0 },
    { "{n}DEC {o}H", 1, 0 },
    { "{n}LD {o}H,$%02X", 2, 2 },
    { "{n}DAA", 1, 0 },
    { "{n}JR {o}Z,$%04X  {e}[%+d]", 2, 5 },
    { "{n}ADD {o}HL,HL", 1, 0 },
    { "{n}LD {o}HL,($%04X)", 3, 3 },
    { "{n}DEC {o}HL", 1, 0 },
    { "{n}INC {o}L", 1, 0 },
    { "{n}DEC {o}L", 1, 0 },
    { "{n}LD {o}L,$%02X", 2, 2 },
    { "{n}CPL", 1, 0 },

    { "{n}JR {o}NC,$%04X  {e}[%+d]", 2, 5 },
    { "{n}LD {o}SP,$%04X", 3, 3 },
    { "{n}LD {o}($%04X),A", 3, 3 },
    { "{n}INC {o}SP", 1, 0 },
    { "{n}INC {o}(HL)", 1, 0 },
    { "{n}DEC {o}(HL)", 1, 0 },
    { "{n}LD {o}(HL),$%02X", 2, 2 },
    { "{n}SCF", 1, 0 },
    { "{n}JR {o}C,$%04X  {e}[%+d]", 2, 5 },
    { "{n}ADD {o}HL,SP", 1, 0 },
    { "{n}LD {o}A,($%04X)", 3, 3 },
    { "{n}DEC {o}SP", 1, 0 },
    { "{n}INC {o}A", 1, 0 },
    { "{n}DEC {o}A", 1, 0 },
    { "{n}LD {o}A,$%02X", 2, 2 },
    { "{n}CCF", 1, 0 },

    { "{n}LD {o}B,B", 1, 0 },
    { "{n}LD {o}B,C", 1, 0 },
    { "{n}LD {o}B,D", 1, 0 },
    { "{n}LD {o}B,E", 1, 0 },
    { "{n}LD {o}B,H", 1, 0 },
    { "{n}LD {o}B,L", 1, 0 },
    { "{n}LD {o}B,(HL)", 1, 0 },
    { "{n}LD {o}B,A", 1, 0 },
    { "{n}LD {o}C,B", 1, 0 },
    { "{n}LD {o}C,C", 1, 0 },
    { "{n}LD {o}C,D", 1, 0 },
    { "{n}LD {o}C,E", 1, 0 },
    { "{n}LD {o}C,H", 1, 0 },
    { "{n}LD {o}C,L", 1, 0 },
    { "{n}LD {o}C,(HL)", 1, 0 },
    { "{n}LD {o}C,A", 1, 0 },

    { "{n}LD {o}D,B", 1, 0 },
    { "{n}LD {o}D,C", 1, 0 },
    { "{n}LD {o}D,D", 1, 0 },
    { "{n}LD {o}D,E", 1, 0 },
    { "{n}LD {o}D,H", 1, 0 },
    { "{n}LD {o}D,L", 1, 0 },
    { "{n}LD {o}D,(HL)", 1, 0 },
    { "{n}LD {o}D,A", 1, 0 },
    { "{n}LD {o}E,B", 1, 0 },
    { "{n}LD {o}E,C", 1, 0 },
    { "{n}LD {o}E,D", 1, 0 },
    { "{n}LD {o}E,E", 1, 0 },
    { "{n}LD {o}E,H", 1, 0 },
    { "{n}LD {o}E,L", 1, 0 },
    { "{n}LD {o}E,(HL)", 1, 0 },
    { "{n}LD {o}E,A", 1, 0 },

    { "{n}LD {o}H,B", 1, 0 },
    { "{n}LD {o}H,C", 1, 0 },
    { "{n}LD {o}H,D", 1, 0 },
    { "{n}LD {o}H,E", 1, 0 },
    { "{n}LD {o}H,H", 1, 0 },
    { "{n}LD {o}H,L", 1, 0 },
    { "{n}LD {o}H,(HL)", 1, 0 },
    { "{n}LD {o}H,A", 1, 0 },
    { "{n}LD {o}L,B", 1, 0 },
    { "{n}LD {o}L,C", 1, 0 },
    { "{n}LD {o}L,D", 1, 0 },
    { "{n}LD {o}L,E", 1, 0 },
    { "{n}LD {o}L,H", 1, 0 },
    { "{n}LD {o}L,L", 1, 0 },
    { "{n}LD {o}L,(HL)", 1, 0 },
    { "{n}LD {o}L,A", 1, 0 },

    { "{n}LD {o}(HL),B", 1, 0 },
    { "{n}LD {o}(HL),C", 1, 0 },
    { "{n}LD {o}(HL),D", 1, 0 },
    { "{n}LD {o}(HL),E", 1, 0 },
    { "{n}LD {o}(HL),H", 1, 0 },
    { "{n}LD {o}(HL),L", 1, 0 },
    { "{n}HALT", 1, 0 },
    { "{n}LD {o}(HL),A", 1, 0 },
    { "{n}LD {o}A,B", 1, 0 },
    { "{n}LD {o}A,C", 1, 0 },
    { "{n}LD {o}A,D", 1, 0 },
    { "{n}LD {o}A,E", 1, 0 },
    { "{n}LD {o}A,H", 1, 0 },
    { "{n}LD {o}A,L", 1, 0 },
    { "{n}LD {o}A,(HL)", 1, 0 },
    { "{n}LD {o}A,A", 1, 0 },

    { "{n}ADD {o}A,B", 1, 0 },
    { "{n}ADD {o}A,C", 1, 0 },
    { "{n}ADD {o}A,D", 1, 0 },
    { "{n}ADD {o}A,E", 1, 0 },
    { "{n}ADD {o}A,H", 1, 0 },
    { "{n}ADD {o}A,L", 1, 0 },
    { "{n}ADD {o}A,(HL)", 1, 0 },
    { "{n}ADD {o}A,A", 1, 0 },
    { "{n}ADC {o}A,B", 1, 0 },
    { "{n}ADC {o}A,C", 1, 0 },
    { "{n}ADC {o}A,D", 1, 0 },
    { "{n}ADC {o}A,E", 1, 0 },
    { "{n}ADC {o}A,H", 1, 0 },
    { "{n}ADC {o}A,L", 1, 0 },
    { "{n}ADC {o}A,(HL)", 1, 0 },
    { "{n}ADC {o}A,A", 1, 0 },

    { "{n}SUB {o}B", 1, 0 },
    { "{n}SUB {o}C", 1, 0 },
    { "{n}SUB {o}D", 1, 0 },
    { "{n}SUB {o}E", 1, 0 },
    { "{n}SUB {o}H", 1, 0 },
    { "{n}SUB {o}L", 1, 0 },
    { "{n}SUB {o}(HL)", 1, 0 },
    { "{n}SUB {o}A", 1, 0 },
    { "{n}SBC {o}A,B", 1, 0 },
    { "{n}SBC {o}A,C", 1, 0 },
    { "{n}SBC {o}A,D", 1, 0 },
    { "{n}SBC {o}A,E", 1, 0 },
    { "{n}SBC {o}A,H", 1, 0 },
    { "{n}SBC {o}A,L", 1, 0 },
    { "{n}SBC {o}A,(HL)", 1, 0 },
    { "{n}SBC {o}A,A", 1, 0 },

    { "{n}AND {o}B", 1, 0 },
    { "{n}AND {o}C", 1, 0 },
    { "{n}AND {o}D", 1, 0 },
    { "{n}AND {o}E", 1, 0 },
    { "{n}AND {o}H", 1, 0 },
    { "{n}AND {o}L", 1, 0 },
    { "{n}AND {o}(HL)", 1, 0 },
    { "{n}AND {o}A", 1, 0 },
    { "{n}XOR {o}B", 1, 0 },
    { "{n}XOR {o}C", 1, 0 },
    { "{n}XOR {o}D", 1, 0 },
    { "{n}XOR {o}E", 1, 0 },
    { "{n}XOR {o}H", 1, 0 },
    { "{n}XOR {o}L", 1, 0 },
    { "{n}XOR {o}(HL)", 1, 0 },
    { "{n}XOR {o}A", 1, 0 },

    { "{n}OR {o}B", 1, 0 },
    { "{n}OR {o}C", 1, 0 },
    { "{n}OR {o}D", 1, 0 },
    { "{n}OR {o}E", 1, 0 },
    { "{n}OR {o}H", 1, 0 },
    { "{n}OR {o}L", 1, 0 },
    { "{n}OR {o}(HL)", 1, 0 },
    { "{n}OR {o}A", 1, 0 },
    { "{n}CP {o}B", 1, 0 },
    { "{n}CP {o}C", 1, 0 },
    { "{n}CP {o}D", 1, 0 },
    { "{n}CP {o}E", 1, 0 },
    { "{n}CP {o}H", 1, 0 },
    { "{n}CP {o}L", 1, 0 },
    { "{n}CP {o}(HL)", 1, 0 },
    { "{n}CP {o}A", 1, 0 },

    { "{n}RET {o}NZ", 1, 0 },
    { "{n}POP {o}BC", 1, 0 },
    { "{n}JP {o}NZ,$%04X", 3, 3 },
    { "{n}JP {o}$%04X", 3, 3 },
    { "{n}CALL {o}NZ,$%04X", 3, 3 },
    { "{n}PUSH {o}BC", 1, 0 },
    { "{n}ADD {o}A,$%02X", 2, 2 },
    { "{n}RST {o}00H", 1, 0 },
    { "{n}RET {o}Z", 1, 0 },
    { "{n}RET", 1, 0 },
    { "{n}JP {o}Z,$%04X", 3, 3 },
    { "{n}CB {o}PREFIX", 1, 0 },
    { "{n}CALL {o}Z,$%04X", 3, 3 },
    { "{n}CALL {o}$%04X", 3, 3 },
    { "{n}ADC {o}A,$%02X", 2, 2 },
    { "{n}RST {o}08H", 1, 0 },

    { "{n}RET {o}NC", 1, 0 },
    { "{n}POP {o}DE", 1, 0 },
    { "{n}JP {o}NC,$%04X", 3, 3 },
    { "{n}OUT {o}($%02X),A", 2, 2 },
    { "{n}CALL {o}NC,$%04X", 3, 3 },
    { "{n}PUSH {o}DE", 1, 0 },
    { "{n}SUB {o}$%02X", 2, 2 },
    { "{n}RST {o}10H", 1, 0 },
    { "{n}RET {o}C", 1, 0 },
    { "{n}EXX", 1, 0 },
    { "{n}JP {o}C,$%04X", 3, 3 },
    { "{n}IN {o}A,($%02X)", 2, 2 },
    { "{n}CALL {o}C,$%04X", 3, 3 },
    { "{n}DD {o}PREFIX", 1, 0 },
    { "{n}SBC {o}A,$%02X", 2, 2 },
    { "{n}RST {o}18H", 1, 0 },

    { "{n}RET {o}PO", 1, 0 },
    { "{n}POP {o}HL", 1, 0 },
    { "{n}JP {o}PO,$%04X", 3, 3 },
    { "{n}EX {o}(SP),HL", 1, 0 },
    { "{n}CALL {o}PO,$%04X", 3, 3 },
    { "{n}PUSH {o}HL", 1, 0 },
    { "{n}AND {o}$%02X", 2, 2 },
    { "{n}RST {o}20H", 1, 0 },
    { "{n}RET {o}PE", 1, 0 },
    { "{n}JP {o}(HL)", 1, 0 },
    { "{n}JP {o}PE,$%04X", 3, 3 },
    { "{n}EX {o}DE,HL", 1, 0 },
    { "{n}CALL {o}PE,$%04X", 3, 3 },
    { "{n}ED {o}PREFIX", 1, 0 },
    { "{n}XOR {o}$%02X", 2, 2 },
    { "{n}RST {o}28H", 1, 0 },

    { "{n}RET {o}P", 1, 0 },
    { "{n}POP {o}AF", 1, 0 },
    { "{n}JP {o}P,$%04X", 3, 3 },
    { "{n}DI", 1, 0 },
    { "{n}CALL {o}P,$%04X", 3, 3 },
    { "{n}PUSH {o}AF", 1, 0 },
    { "{n}OR {o}$%02X", 2, 2 },
    { "{n}RST {o}30H", 1, 0 },
    { "{n}RET {o}M", 1, 0 },
    { "{n}LD {o}SP,HL", 1, 0 },
    { "{n}JP {o}M,$%04X", 3, 3 },
    { "{n}EI", 1, 0 },
    { "{n}CALL {o}M,$%04X", 3, 3 },
    { "{n}FD {o}PREFIX", 1, 0 },
    { "{n}CP {o}$%02X", 2, 2 },
    { "{n}RST {o}38H", 1, 0 }
};

#endif	/* OPCODEXX_NAMES_H */

